<?php

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
function visitor_motivation_survey_help($path, $arg) {
  switch ($path) {
    case "admin/help#visitor_motivation_survey":
      return '<p>' . t("Activates Spellerberg Associates' Visitor Motivation Survey for data collection") . '</p>';
      break;
  }
} 


/**
 * Implements hook_page_build().
 *
 * Adds the VMS onto pages on the bottom.
 *
 * @param page   
 *   Array of page elements where we'll insert the page block
 *
 */


function visitor_motivation_survey_page_alter(&$page) {
    if (!path_is_admin(current_path())) {
	$page['content']['vms'] = array(
            '#markup' =>  '
		<div class="vms">
                    <div class="xbutton dismiss">Not now <span>&times;</span></div>
                    <div class="xbutton shrink">Close <span>&times;</span></div>
                    <div class="xbutton finish">Close <span>&times;</span></div>
                    <div class="margin">
                        <div class="opensurvey">
                            <div class="prompt clickable">Answer one question. <span>Improve our website.</span></div>
                            <div class="survey">
                                <p>Today, I&rsquo;m visiting the [museum name] website:</p>
                                    <ul>
                                        <li><a class="recharger" href="#">For inspiration.</a></li>
					<li><a class="explorer" href="#">To learn something new.</a></li>
					<li><a class="facilitator" href="#">To plan an activity for my family/friends.</a></li>
					<li><a class="seeker" href="#">Because the [museum name]  was recommended to me.</a></li>
					<li><a class="professional" href="#">For professional reasons.</a></li>
                                    </ul>
                                    <p class="done">Done. Thank you!</p>
                                    <p class="infobutton clickable">What is this?</p>
                                    <p class="infotext">We&rsquo;re always looking for ways to improve our site, so we want to know why you&rsquo;re here and how we can help you find the information you need. For specific questions or comments about our website or this survey, please <a href="[contact]">contact us</a>. Thanks for your help!</p>
                            </div>
			</div>
                    </div>
                    <div class="mquery"></div>
		  </div>
		  ',
		  '#weight' => 120
		);   
    }

}
