<?php

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
function visitor_motivation_survey_help($path, $arg) {
  switch ($path) {
    case "admin/help#visitor_motivation_survey":
      return '<p>' . t("Activates Spellerberg Associates' Visitor Motivation Survey for data collection") . '</p>';
      break;
  }
} 


/**
 * Implements hook_page_build().
 *
 * Adds the VMS onto pages on the bottom.
 *
 * @param page   
 *   Array of page elements where we'll insert the page block
 *
 */


function visitor_motivation_survey_page_alter(&$page) {
    if (!path_is_admin(current_path())) {
	$page['content']['vms'] = array(
          '#theme' => 'visitor_motivation_survey',
          '#weight' => 120,
	);   
    }
}

/**
* Implements hook_theme().
* 
*/

function visitor_motivation_survey_theme() {
  return array(
    'visitor_motivation_survey' => array(
      'variables' => array(
        'site_name' => variable_get('site_name', 'drupal'),
      ),  
      // Use a template file called visitor_motivation_survey.tpl.php
      'template' => 'visitor_motivation_survey',
    ),
  );
}
